export enum AccountAuditEvent {
  DEACTIVATED = "DEACTIVATED",
  REACTIVATED = "REACTIVATED",
  DELETION_REQUESTED = "DELETION_REQUESTED",
  DELETION_CANCELLED = "DELETION_CANCELLED",
  DELETION_EXECUTED = "DELETION_EXECUTED",
}
