export enum AccountDeletionReason {
  NOT_USING_ANYMORE = "NOT_USING_ANYMORE",
  PRIVACY_CONCERNS = "PRIVACY_CONCERNS",
  FOUND_ALTERNATIVE = "FOUND_ALTERNATIVE",
  HARD_TO_USE = "HARD_TO_USE",
  TECHNICAL_ISSUES = "TECHNICAL_ISSUES",
  OTHER = "OTHER",
}
