export enum AccountDeactivationReason {
  NOT_USING_ANYMORE = "NOT_USING_ANYMORE",
  TAKING_A_BREAK = "TAKING_A_BREAK",
  TOO_MANY_NOTIFICATIONS = "TOO_MANY_NOTIFICATIONS",
  FOUND_ALTERNATIVE = "FOUND_ALTERNATIVE",
  HARD_TO_USE = "HARD_TO_USE",
  OTHER = "OTHER",
}
