export enum CancellationReason {
  DOES_NOT_MEET_NEEDS = "DOES_NOT_MEET_NEEDS",
  TOO_EXPENSIVE = "TOO_EXPENSIVE",
  FOUND_ALTERNATIVE = "FOUND_ALTERNATIVE",
  HARD_TO_USE = "HARD_TO_USE",
  MISSING_FEATURES = "MISSING_FEATURES",
  TEMPORARY_USE = "TEMPORARY_USE",
  TECHNICAL_ISSUES = "TECHNICAL_ISSUES",
  OTHER = "OTHER",
}
