export interface CreateGatewayCustomerInput {
  name: string;
  email: string;
  cpfCnpj: string;
  externalReference: string;
}

export interface CreateGatewayCustomerResult {
  gatewayCustomerId: string;
}

export interface CreateGatewaySubscriptionInput {
  gatewayCustomerId: string;
  value: number;
  nextDueDate: string;
  cycle: string;
  description: string;
  externalReference: string;
  // Where Asaas sends the customer back after paying the invoice, so they
  // aren't stranded on Asaas' own checkout page. Applies to every future
  // invoice generated by this subscription too, not just the first one.
  callbackSuccessUrl?: string;
}

export interface CreateGatewaySubscriptionResult {
  gatewaySubscriptionId: string;
  status: string;
  checkoutUrl?: string;
  // The gateway's own id for the first invoice this subscription generated
  // — needed to override just that one payment's value for the first-month
  // discount (see SubscribeToProUseCase). Every later invoice keeps the
  // subscription's regular value.
  firstPaymentId?: string;
}

export interface CreatePixAutomaticAuthorizationInput {
  gatewayCustomerId: string;
  value: number;
  frequency: string;
  contractId: string;
  startDate: string;
  description: string;
  // Overrides just the immediate/first charge's amount, independent of
  // `value` (which governs every recurring charge after it) — used for the
  // first-month discount. Falls back to `value` when omitted.
  firstChargeValue?: number;
}

export interface CreatePixAutomaticAuthorizationResult {
  pixAutomaticAuthorizationId: string;
  status: string;
  qrCodePayload?: string;
  qrCodeImage?: string;
}

export interface CreatePixTransferInput {
  // Reais, not cents — the gateway's own API works in decimal currency
  // units, matching every other value field on this port.
  value: number;
  pixAddressKey: string;
  pixAddressKeyType: string;
  description: string;
  externalReference: string;
}

export interface CreatePixTransferResult {
  gatewayTransferId: string;
  status: string;
  failReason?: string;
}

export interface LookupPixKeyInput {
  pixKeyType: string;
  pixKey: string;
}

export interface LookupPixKeyResult {
  bankName: string;
  ownerName: string;
  ownerDocument: string;
}

export interface PaymentGatewayPort {
  createCustomer(
    input: CreateGatewayCustomerInput,
  ): Promise<CreateGatewayCustomerResult>;
  createSubscription(
    input: CreateGatewaySubscriptionInput,
  ): Promise<CreateGatewaySubscriptionResult>;
  createPixAutomaticAuthorization(
    input: CreatePixAutomaticAuthorizationInput,
  ): Promise<CreatePixAutomaticAuthorizationResult>;
  cancelSubscription(gatewaySubscriptionId: string): Promise<void>;
  cancelPixAutomaticAuthorization(
    pixAutomaticAuthorizationId: string,
  ): Promise<void>;
  createPixTransfer(
    input: CreatePixTransferInput,
  ): Promise<CreatePixTransferResult>;
  // Overrides the value of a single already-generated, still-pending
  // payment — used to discount a checkout subscription's first invoice
  // without touching the ones after it.
  updatePaymentValue(gatewayPaymentId: string, value: number): Promise<void>;
  lookupPixKey(input: LookupPixKeyInput): Promise<LookupPixKeyResult>;
}

export const PAYMENT_GATEWAY = Symbol("PAYMENT_GATEWAY");
