export interface CreateGatewayCustomerInput {
  name: string;
  email: string;
  cpfCnpj: string;
  externalReference: string;
}

export interface CreateGatewayCustomerResult {
  gatewayCustomerId: string;
}

export interface CreateGatewaySubscriptionInput {
  gatewayCustomerId: string;
  value: number;
  nextDueDate: string;
  cycle: string;
  description: string;
  externalReference: string;
  // Where Asaas sends the customer back after paying the invoice, so they
  // aren't stranded on Asaas' own checkout page. Applies to every future
  // invoice generated by this subscription too, not just the first one.
  callbackSuccessUrl?: string;
}

export interface CreateGatewaySubscriptionResult {
  gatewaySubscriptionId: string;
  status: string;
  checkoutUrl?: string;
}

export interface CreatePixAutomaticAuthorizationInput {
  gatewayCustomerId: string;
  value: number;
  frequency: string;
  contractId: string;
  startDate: string;
  description: string;
}

export interface CreatePixAutomaticAuthorizationResult {
  pixAutomaticAuthorizationId: string;
  status: string;
  qrCodePayload?: string;
  qrCodeImage?: string;
}

export interface PaymentGatewayPort {
  createCustomer(
    input: CreateGatewayCustomerInput,
  ): Promise<CreateGatewayCustomerResult>;
  createSubscription(
    input: CreateGatewaySubscriptionInput,
  ): Promise<CreateGatewaySubscriptionResult>;
  createPixAutomaticAuthorization(
    input: CreatePixAutomaticAuthorizationInput,
  ): Promise<CreatePixAutomaticAuthorizationResult>;
  cancelSubscription(gatewaySubscriptionId: string): Promise<void>;
  cancelPixAutomaticAuthorization(
    pixAutomaticAuthorizationId: string,
  ): Promise<void>;
}

export const PAYMENT_GATEWAY = Symbol("PAYMENT_GATEWAY");
