export enum ExportResource {
  DEBTS = "DEBTS",
  PAYMENTS = "PAYMENTS",
  INCOMES = "INCOMES",
  INCOME_RECEIPTS = "INCOME_RECEIPTS",
  CREDIT_CARDS = "CREDIT_CARDS",
  CATEGORIES = "CATEGORIES",
  STATEMENT = "STATEMENT",
  GOALS = "GOALS",
  GOAL_CONTRIBUTIONS = "GOAL_CONTRIBUTIONS",
}
