export enum AuthPermission {
  CHANGE_OWN_PASSWORD = "CHANGE_OWN_PASSWORD",
  LOGOUT = "LOGOUT",
  MANAGE_OWN_DEBTS = "MANAGE_OWN_DEBTS",
  MANAGE_OWN_PROFILE = "MANAGE_OWN_PROFILE",
  MANAGE_OWN_USER = "MANAGE_OWN_USER",
  MANAGE_USERS = "MANAGE_USERS",
  READ_OWN_DEBTS = "READ_OWN_DEBTS",
  READ_OWN_PROFILE = "READ_OWN_PROFILE",
  READ_OWN_USER = "READ_OWN_USER",
  READ_PROFILES = "READ_PROFILES",
  READ_USERS = "READ_USERS",
}
