export enum PageAccessKey {
  DASHBOARD = "DASHBOARD",
  CATEGORIES = "CATEGORIES",
  DEBTS = "DEBTS",
  DEBTS_STATEMENT = "DEBTS_STATEMENT",
  INCOMES = "INCOMES",
  PAYMENTS = "PAYMENTS",
  INCOME_RECEIPTS = "INCOME_RECEIPTS",
  CREDIT_CARDS = "CREDIT_CARDS",
  ADMIN = "ADMIN",
}

export const ALL_PAGE_ACCESS_KEYS: PageAccessKey[] = [
  PageAccessKey.DASHBOARD,
  PageAccessKey.CATEGORIES,
  PageAccessKey.DEBTS,
  PageAccessKey.DEBTS_STATEMENT,
  PageAccessKey.INCOMES,
  PageAccessKey.PAYMENTS,
  PageAccessKey.INCOME_RECEIPTS,
  PageAccessKey.CREDIT_CARDS,
  PageAccessKey.ADMIN,
];
